# Generated by Django 4.2.6 on 2023-10-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="additional_identifier",
            field=models.CharField(
                blank=True,
                help_text="can be used eg. to differentiate employees with the same name or\n        one person working on more than one position",
                max_length=50,
                null=True,
                verbose_name="additional_identifier",
            ),
        ),
    ]
