# Generated by Django 4.2.6 on 2023-11-07 07:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="name"),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="short name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.CreateModel(
            name="EmployeeDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="date from")),
                (
                    "date_to",
                    models.DateField(blank=True, null=True, verbose_name="date to"),
                ),
            ],
            options={
                "db_table": "tbl_employee_department",
            },
        ),
        migrations.CreateModel(
            name="EmployeePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="date from")),
                (
                    "date_to",
                    models.DateField(blank=True, null=True, verbose_name="date to"),
                ),
            ],
            options={
                "db_table": "tbl_employee_position",
            },
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("W", "woman"), ("M", "man"), ("N", "not specified")],
                        default="N",
                        max_length=2,
                        verbose_name="gender",
                    ),
                ),
                (
                    "work_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="work email"
                    ),
                ),
                (
                    "is_manager",
                    models.CharField(
                        choices=[
                            ("CEO", "CEO"),
                            ("TM", "Top Manager"),
                            ("M", "Manager"),
                            ("N", "Not Manager"),
                        ],
                        default="N",
                        max_length=3,
                        verbose_name="is manager",
                    ),
                ),
                (
                    "annual_leave",
                    models.PositiveIntegerField(
                        default=26, verbose_name="annual leave entitlement"
                    ),
                ),
                (
                    "current_leave",
                    models.IntegerField(
                        default=0, verbose_name="current leave entitlement"
                    ),
                ),
                (
                    "date_hire",
                    models.DateField(blank=True, null=True, verbose_name="hire date"),
                ),
                (
                    "contract_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="contract end"
                    ),
                ),
                (
                    "additional_info",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="additional information",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Profile",
                "verbose_name_plural": "Employees Profiles",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "code",
                    models.PositiveIntegerField(
                        blank=True, verbose_name="position code"
                    ),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("core", "core position"),
                            ("helper", "helper position"),
                        ],
                        default="core",
                        max_length=10,
                        verbose_name="position_type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Posision",
                "verbose_name_plural": "Positions",
            },
        ),
        migrations.CreateModel(
            name="WorkingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="date from")),
                (
                    "date_to",
                    models.DateField(blank=True, null=True, verbose_name="date to"),
                ),
                (
                    "working_time",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=3,
                        verbose_name="working time",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.employeeprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "WorkingTime",
                "verbose_name_plural": "WorkingTime",
            },
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="position",
            field=models.ManyToManyField(
                related_name="employee_position_value",
                through="profiles.EmployeePosition",
                to="profiles.position",
            ),
        ),
    ]
