# Generated by Django 4.2.6 on 2023-11-07 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="workplace",
            field=models.ManyToManyField(
                related_name="employee_department_value",
                through="profiles.EmployeeDepartment",
                to="profiles.department",
                verbose_name="department",
            ),
        ),
        migrations.AddField(
            model_name="employeeposition",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_position_value_e",
                to="profiles.employeeprofile",
            ),
        ),
        migrations.AddField(
            model_name="employeeposition",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_position_value_p",
                to="profiles.position",
            ),
        ),
        migrations.AddField(
            model_name="employeedepartment",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_department_value_d",
                to="profiles.department",
            ),
        ),
        migrations.AddField(
            model_name="employeedepartment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_department_value_ec",
                to="profiles.employeeprofile",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="manager",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeeposition",
            unique_together={("employee", "position")},
        ),
        migrations.AlterUniqueTogether(
            name="employeedepartment",
            unique_together={("employee", "department")},
        ),
    ]
